# Task 3 & 6 – CD: Staging → Production (Environment "Production" = approval). Secrets: AZURE_*, KEY_VAULT_NAME, APP_SERVICE_NAME_*
name: CD

on:
  workflow_run:
    workflows: [CI]
    types: [completed]
    branches: [main]
  workflow_dispatch:

jobs:
  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch'
    environment: Staging

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download CI artifact
        if: github.event.workflow_run.id != ''
        uses: actions/download-artifact@v4
        with:
          name: drop
          run-id: ${{ github.event.workflow_run.id }}

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Get secrets from Key Vault
        id: keyvault
        uses: Azure/get-keyvault-secrets@v1
        with:
          keyvault: ${{ secrets.KEY_VAULT_NAME }}
          secrets: 'AppConnectionString ApiKey'
        continue-on-error: true

      - name: Deploy to Azure Web App (Staging)
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.APP_SERVICE_NAME_STAGING }}
          package: .

  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: deploy-staging
    environment: Production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download CI artifact
        if: github.event.workflow_run.id != ''
        uses: actions/download-artifact@v4
        with:
          name: drop
          run-id: ${{ github.event.workflow_run.id }}

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Get secrets from Key Vault
        id: keyvault
        uses: Azure/get-keyvault-secrets@v1
        with:
          keyvault: ${{ secrets.KEY_VAULT_NAME }}
          secrets: 'AppConnectionString ApiKey'
        continue-on-error: true

      - name: Deploy to Azure Web App (Production)
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.APP_SERVICE_NAME_PROD }}
          package: .
