# Task 14 – Fixed: set env.APP_ENV in workflow so deploy step has it
name: Pipeline Debugging (Fixed)

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/pipeline-debugging.yml'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      APP_ENV: development
    steps:
      - run: echo "Building for $APP_ENV"
      - run: echo "Publishing..."

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    environment: Staging
    env:
      APP_ENV: development
    steps:
      - run: |
          echo "Deploying to environment: $APP_ENV"
          if [ -z "$APP_ENV" ]; then
            echo "ERROR: APP_ENV is not set"
            exit 1
          fi
          echo "Deploy completed successfully."
